#pragma kernel CSMain

RWTexture3D<float4> _TargetTex; // clear target
uint _TexelSize;

[numthreads(64, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    uint index = id.x;
    uint size = _TexelSize;
    uint x, y, z;

    z = floor(index / (size * size));
    uint i = index - z * size * size;
    y = floor(i / size);
    x = i - y * size;

    uint3 pixelPos = uint3(x, y, z);
    _TargetTex[pixelPos] = float4(0, 0, 0, 0);
}
